<a href="https://colab.research.google.com/github/Moxammed/Data-Science-and-ML/blob/main/1-%20Tensorflow_Learn_gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

t = tf.constant([ [1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9] ])

In [ ]:
#1.	Extract the second column.

col2= t[:,1]
print(col2)


tf.Tensor([2 5 8], shape=(3,), dtype=int32)


In [ ]:
#2.	Extract the first two rows.

twoRows= t[0:2,:]
print(twoRows)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
#3.	Reverse the rows.

revRows=t[::-1]
print(revRows)

tf.Tensor(
[[7 8 9]
 [4 5 6]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [ ]:
#4.	Extract the submatrix:
# 5, 6
# 8, 9

sub=t[1:, 1:]
print(sub)

tf.Tensor(
[[5 6]
 [8 9]], shape=(2, 2), dtype=int32)


**Tensor Operations**

In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

In [ ]:
#1.	Add x and y.
z=x+y

print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
#2.	Multiply x and y elementwise.

mul=x*y
print(mul)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [ ]:
#3.	Compute dot product of x and y.

dotProduct=tf.tensordot(x,y,axes=1)
print(dotProduct)

tf.Tensor(32, shape=(), dtype=int32)


In [ ]:
#4.	Compute x squared elementwise.

arrSquared= x**y
print(arrSquared)

tf.Tensor([  1  32 729], shape=(3,), dtype=int32)


In [ ]:
#5.	Compute mean and standard deviation of y.
arrMean= tf.reduce_mean(y)

yNew= tf.cast(y,tf.float32)
arrSTD = tf.math.reduce_std(yNew)

print(arrMean)
print(arrSTD)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(0.8164966, shape=(), dtype=float32)




**4️⃣ Broadcasting & Reshaping**


In [ ]:
#1.	Create a (2,3) tensor and a (3,) tensor. Add them using broadcasting.

twoByThree= tf.random.uniform(shape=(2,3), minval=1,maxval=20, dtype=tf.int32)
three= tf.random.uniform(shape=(3,),minval=1, maxval=100, dtype=tf.int32)

print(twoByThree)
print(three)

print("Addition is as follows")
add= twoByThree + three
print(add)


tf.Tensor(
[[14  8 12]
 [18  3 14]], shape=(2, 3), dtype=int32)
tf.Tensor([12 40  1], shape=(3,), dtype=int32)
Addition is as follows
tf.Tensor(
[[26 48 13]
 [30 43 15]], shape=(2, 3), dtype=int32)


In [ ]:
#2.	Reshape a (6,) tensor into (2,3) shape.

six=tf.random.uniform((6,), minval=1, maxval=100, dtype=tf.int32)
print(six)

reshaped=tf.reshape(six,(2,3))
print(reshaped)

tf.Tensor([74 82 31 11 83 20], shape=(6,), dtype=int32)
tf.Tensor(
[[74 82 31]
 [11 83 20]], shape=(2, 3), dtype=int32)


In [ ]:
#3.	Flatten a (3,3) tensor into a 1D tensor.
three=tf.random.uniform((3,3), minval=1, maxval=100, dtype=tf.int32)
print(three)

flattened=tf.reshape(three,[-1])
print(flattened)

tf.Tensor(
[[14 35 87]
 [70 87 10]
 [50 52 20]], shape=(3, 3), dtype=int32)
tf.Tensor([14 35 87 70 87 10 50 52 20], shape=(9,), dtype=int32)


In [ ]:
#4.	Transpose a (2,3) tensor into (3,2).

arrTwo= tf.random.uniform((2,3), minval=1, maxval=100, dtype=tf.int32)
print(arrTwo)

transposed = tf.transpose(arrTwo)
print(transposed)

tf.Tensor(
[[34 10 88]
 [23 36 98]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[34 23]
 [10 36]
 [88 98]], shape=(3, 2), dtype=int32)


In [ ]:
import tensorflow as tf

x = tf.Variable(5.0)

with tf.GradientTape() as tape:
    y = x**2 + 3*x + 2

dy_dx = tape.gradient(y, x)
print(dy_dx)


tf.Tensor(13.0, shape=(), dtype=float32)
